# ============================================
# SoundCloud configuration
# ============================================

AUDIO_FORMAT="mp3"
AUDIO_QUALITY="0"         # 0 = best, 10 = worst
DOWNLOAD_PATH="dl"
